# -*- coding: utf-8 -*-
"""busqueda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f_EbJ3v_0bymHG3IEYrmrPRZQ8S2pgeg
"""

# Libreria de Busqueda
# Fabian Trigo, @fbientrigo en Github


import requests                 # Para obtener datos de la pagina _____
from bs4 import BeautifulSoup as bs

# Descargar la pagina web ______________________________________________________
def get_page(aniurl):
    """
    Utilzamos beautiful soup y request para obtener la url y obtener la pagina
    como texto separado por linea dentro de una lista, esta funcion devuelve una
    lista

    >> get_page("https://github.com/fbientrigo/PythonLibreria")
        >> <!DOCTYPE html> == $0 \\n <html la...
    
    """
    #descargamos la pagina
    page = requests.get(aniurl)
    #la ordenamos
    soup = bs(page.content, 'html.parser')

    # separamos cada linea en elementos de una lista
    page = str(soup).split("\n")

    return page

# Buscador de palabras ________________________________________________________
def grep(texto, buscar, imprimir = False):
    """
    #Comparador de Lineas
    ingrese string en el texto y buscar, en caso de que el texto contenga la palabra
    que reemplazo por buscar, se imprimira la linea donde aparecio

    >> grep("hola \\n como estas","estas")
        > "como estas"
    """
    #Separamos el texto en lineas
    #texto = str(texto).split("\n")

    for linea in texto:
        if buscar in linea:
            if imprimir:
                print(linea)
            else:
                return linea